language: rust
rust:
  - stable
  - nightly
  - 1.44.1

jobs:
  fast_finish: true

cache: cargo

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - echo rust version is "$TRAVIS_RUST_VERSION"
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then RUSTFLAGS="-Z sanitizer=address" cargo run --example arc-sanitize --target x86_64-unknown-linux-gnu; fi

notifications:
  email:
    on_success: never
