[package]
name = "internment"
version = "0.5.0"
authors = ["David Roundy <roundyd@physics.oregonstate.edu>"]
edition = "2018"

description = "Easy interning of data"
license = "MIT/Apache-2.0"
repository = "https://github.com/droundy/internment"

readme = "README.md"
categories = ["caching", "memory-management", "concurrency"]
keywords = ["hash", "interning", "hashconsing", "caching", "interner"]

[badges]

appveyor = { repository = "droundy/internment" }
travis-ci = { repository = "droundy/internment" }
coveralls = { repository = "droundy/internment" }

is-it-maintained-issue-resolution = { repository = "droundy/internment" }
is-it-maintained-open-issues = { repository = "droundy/internment" }
maintenance = { status = "actively-developed" }

[dependencies]

parking_lot = "0.11.0"
dashmap = { version = "3.11.9", optional = true }
once_cell = "1.4"
tinyset = { version = "0.4.2", optional =  true }
hashbrown = { version = "0.9" }
serde = { version = "1.0", optional = true }

arc-interner = { version = "0.5", optional = true }

[features]

arc = ["dashmap"]
bench = ["arc", "arc-interner"]

[dev-dependencies]

quickcheck = "^0.9.2"
scaling = "0.1.3"
rand = "0.7.2"

[[bench]]
name = "bench"
harness = false
