[package]
name = "internment"
version = "0.2.1"
authors = ["David Roundy <roundyd@physics.oregonstate.edu>"]

description = "Easy interning of data"
license = "MPL-2.0"
repository = "https://github.com/droundy/internment"


[dependencies]

lazy_static = "1.0"

state = { version = "0.4", features = ["tls"] }

tinyset = "0.0.12"
