branch: true
ignore-not-existing: true
llvm: true
filter: covered
output-type: lcov
output-path: ./my-lcov.info
keep-only:
  - "src/*"
ignore:
  - "*.cargo/*"
excl-line: "#.derive.+"
excl-start: "#.+test..?$"
excl-stop: "^$"
