branch: true
ignore-not-existing: true
llvm: true
filter: covered
output-type: lcov
output-path: ./lcov.info
keep-only:
  - "src/*"
excl-br-line: "#\\[(derive(.*)\\]"
excl-br-start: "#\\[test\\]"
excl-br-stop: "^\\}$"
